# Generated by Django 5.1 on 2025-03-22 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_profile_date_of_birth_profile_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='users/profile.png', upload_to='users/%Y/%m/%d'),
        ),
    ]
