# Generated by Django 5.1 on 2025-04-12 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='https://re.cloudinary.com/dhj7zo5li/image/upload/v1744415629/user/profile.png', upload_to='users/'),
        ),
    ]
