# Generated by Django 5.1 on 2025-03-30 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_post_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='like',
            new_name='likes',
        ),
    ]
