# Generated by Django 5.1 on 2025-03-31 10:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_rename_like_post_likes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendship',
            old_name='user',
            new_name='follower',
        ),
        migrations.RenameField(
            model_name='friendship',
            old_name='friend',
            new_name='following',
        ),
        migrations.AlterUniqueTogether(
            name='friendship',
            unique_together={('follower', 'following')},
        ),
    ]
