# Generated by Django 5.1 on 2025-04-01 06:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_rename_user_friendship_follower_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='post_following', to=settings.AUTH_USER_MODEL),
        ),
    ]
